services:
  postgres:
    image: postgres:16
    container_name: bank_postgres
    environment:
      POSTGRES_USER: bank_admin
      POSTGRES_PASSWORD: bank_password
      POSTGRES_DB: bank_dw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank_admin -d bank_dw"]
      interval: 5s
      timeout: 5s
      retries: 10

  metabase:
    image: metabase/metabase:latest
    container_name: bank_metabase
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
